---
# This playbook deploys the entire application stack.

- hosts: gitlab
  tasks:
    - name: Configure Gitlab Yum repository
      yum_repository:
        name: gitlab-ce
        description: Gitlab Community repo
        file: gitlab_ce
        baseurl: https://packages.gitlab.com/gitlab/gitlab-ce/el/6/$basearch
        gpgcheck: yes
        gpgkey:
          - https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
          - https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg
        repo_gpgcheck: yes
        metadata_expire: 300
        sslverify: yes
      notify: "yum repos changed"
    - name: Configure Gitlab Source Yum repo
      yum_repository:
        name: gitlabe-ce-source
        description: Gitlab Community Source repo
        file: gitlab_ce
        baseurl: https://packages.gitlab.com/gitlab/gitlab-ce/el/6/SRPMS
        gpgcheck: yes
        gpgkey:
          - https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
          - https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg
        repo_gpgcheck: yes
        metadata_expire: 300
        sslverify: yes
      notify: "yum repos changed"
    - name: Install Gitlab dependencies
      yum:
        name:
          - policycoreutils-python
          - cronie
        state: latest
    - name: Install Gitlab
      yum:
        name: gitlab-ce
        state: latest
      notify: "gitlab updated"
  handlers:
    - name: yum-clean-metadata
      command: yum clean metadata
      args:
        warn: no
      listen: "yum repos changed"
    - name: gitlab-ctl-reconfigure
      command: gitlab-ctl reconfigura
      listen: "gitlab updated"


# TODO(aidanns): Enable systemd on the container so that this installation works.
# TODO(aidanns): Configure firewall.
# TODO(aidannS): Put Gitlab behind Nginx.
